src/Factory.php, src/JsValidator.php
@torrentalle requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/proengsoft/laravel-jsvalidation/
=> Scrutinizer Auto-Fixes

resources/views/bootstrap.php
Displaying checkbox errors with correct styling.
=> Support for checkboxes

composer.json
=> Allow Laravel 5.1

CHANGELOG.md, src/Traits/JavascriptRules.php, src/Traits/RemoteValidation.php, src/Validator.php, tests/ValidatorTest.php
Fix input some validations when the attribute or field name parameters are array's
=> Fix some validations when field is array

.travis.yml, composer.json, tests/composer-5.0.json, tests/composer-5.1.json, tests/composer-5.2.json, tests/composer-5.3.json
Add build matrix for Travis to test all Laravel verions with compiteble PHP's version
=> Travis build with multiple Laravel versions

resources/assets/js/validations.js, src/Support/RuleListTrait.php
=> Code style

.scrutinizer.yml, src/Remote/Resolver.php, src/Remote/Validator.php, src/RemoteValidationMiddleware.php, tests/Remote/ResolverTest.php, tests/Remote/ValidatorTest.php
=> Remote validation refactoring

.travis.yml
=> Fix phpunit path

.travis.yml, composer.json
Prevent using package on Laravel > 5.4 and move tests files namespace to `autoload-dev`.
=> Fix Laravel versions support

CHANGELOG.md, resources/assets/js/helpers.js
=> Fix guessDate method name typo

CHANGELOG.md, CONTRIBUTING.md, README.md, composer.json
- Added Contributing guide.
- Added diff links to changelog.
- Add list of contributors on main page.
=> Add more package meta information

composer.json
=> Add Laravel 5.5 support

resources/views/bootstrap4.php
#321 
Previous PR: https://github.com/proengsoft/laravel-jsvalidation/pull/324
=> Support for Bootstrap 4.1

composer.json
Tests are incompatible with PHPUnit 8
=> Removed phpunit ^8.0 from require-dev

composer.json, phpunit.xml.dist, tests/Facades/JsVaidatorFacadeTest.php, tests/Javascript/JavascriptRulesTraitTest.php, tests/Javascript/JavascriptValidatorTest.php, tests/Javascript/MessageParserTest.php, tests/Javascript/RuleParserTest.php, tests/Javascript/ValidatorHandlerTest.php, tests/JsValidationServiceProviderTest.php, tests/JsValidatorFactoryTest.php, tests/Remote/ResolverTest.php, tests/Remote/ValidatorTest.php, tests/RemoteValidationMiddlewareTest.php, tests/Support/AccessProtectedTraitTest.php, tests/Support/DelegatedValidatorTest.php, tests/Support/RuleListTraitTest.php, tests/Support/UseDelegatedValidatorTraitTest.php, tests/TestCase.php, tests/composer-5.6.json, tests/composer-5.7.json, tests/composer-5.8.json, tests/composer-6.0.json, tests/composer-7.0.json, tests/stubs/ResolverTest.php
Added `orchestra/testbench` so that we can test what's being returned from Laravel. At the moment all of that is mocked so if something changes in Laravel then we can't test against it.
I had to change some of the mocks because `Mockery::close()` wasn't being called so non of the expectations we're previously being checked. All of the ones I changed were broken (an expectation incorrectly ran).
=> Added orchestra/testbench

src/Support/RuleListTrait.php
Moved `Url` validation from client side (JS) to server side (PHP)
=> Closes #232

config/jsvalidation.php
Does what it says on the tin.
Breaking change.
=> All validation messages are now escaped by default.

CHANGELOG.md
=> Update CHANGELOG.md for v4.2.0

src/JsValidatorFactory.php
See https://github.com/proengsoft/laravel-jsvalidation/issues/495
=> Allow type-hint any dependencies in roles()

CHANGELOG.md
=> Update CHANGELOG.md for 4.3.0

.github/workflows/tests.yml, composer.json, tests/composer-5.6.json, tests/composer-5.7.json, tests/composer-5.8.json, tests/composer-6.0.json, tests/composer-7.0.json, tests/composer-8.0.json
Replaced dynamic downloading of ocular with composer dependency which is cached.
=> chore: add scrutinizer/ocular dependency

.github/workflows/coverage.yml, .github/workflows/tests.yml, composer.json, tests/composer-5.6.json, tests/composer-5.7.json, tests/composer-5.8.json, tests/composer-6.0.json, tests/composer-7.0.json, tests/composer-8.0.json
Scruntizer CI needs a job which runs on `dev-master` to send a code coverage report.
=> ci: add code coverage job

.github/workflows/tests.yml
=> ci: test on php 8

config/jsvalidation.php, resources/views/bootstrap5.php
Added fix for issue #728
Added bootstrap5.php to resources file, updated javascript logic to comply with bootstrap 5 validation formatting.
=> feat: add bootstrap5 layout

src/Exceptions/PropertyNotFoundException.php, src/Javascript/JavascriptRulesTrait.php, src/Javascript/JavascriptValidator.php, src/Javascript/MessageParser.php, src/Javascript/RuleParser.php, src/Javascript/ValidatorHandler.php, src/JsValidatorFactory.php, src/Remote/Resolver.php, src/Remote/Validator.php, src/RemoteValidationMiddleware.php, src/Support/AccessProtectedTrait.php, src/Support/DelegatedValidator.php, src/Support/RuleListTrait.php, src/Support/UseDelegatedValidatorTrait.php, src/Support/ValidationRuleParserProxy.php
=> chore: style ci fixes

.github/workflows/php-tests.yml
=> ci: test against php 8.1

.github/workflows/release.yml, release.config.js
=> fix: push public/ assets on release

.github/workflows/php-tests.yml, composer.json, tests/JsValidatorFactoryTest.php
=> feat: laravel 9 support

.github/workflows/release.yml, release.config.js
=> fix: push public/ on release

.github/dependabot.yml
=> chore: group npm dependabot updates

.github/workflows/release.yml
=> chore: update release.yml to use node 20
