proengsoft/laravel-jsvalidation

- config/jsvalidation.php
- resources/views/bootstrap.php
Hello:
I fork your repository to add a new feature in your component:
When We are validating the form I want to move the view to the first error and set the focus on the first component on my form.
I added two new parameters on the config to active or not this feature and to control the time of the animate to move the scroll.
Thank you
Samuel
> Added control to focus on components when the form has some errors

- resources/assets/js/jsvalidation.js
Given the fact that PUT is not a valid method of a form, we need to get the actual method of the route which can be found in html as "_method"
> Bugfix - Validate PUT methods on remote

- src/Traits/JavascriptRules.php
- src/Traits/RemoteValidation.php
- src/Validator.php
Adds support for validations like: data.name which is data[name] in view.
Example:
FormRequest file:
```php
return [
'data.en.name' => 'integer',
'data.start_date' => 'required|date_format:d/m/Y|before:tomorrow',
];
```
View file
```php
Form::input('data[en][name]')
```
> Support multidimensional array validation

- resources/views/bootstrap.php
- src/JsValidationServiceProvider.php
- src/JsValidatorFactory.php
- src/Manager.php
* permit multiple validator instances so subsequent calls to `JsValidator::make()` and `JsValidator::formRequest()` don't overwrite the previous selector + validator. Some justification for this implementation can be found at https://github.com/proengsoft/laravel-jsvalidation/issues/87
* add `ignore()` method to the JsValidator facade so a jQuery selector may be defined per-form as this is the typical use case for jQuery Validator's 'ignore' option. Custom non-Bootstrap views may optionally implement this functionality. Example usage:
```php
$jsValidator = JsValidator::make($rules);
$jsValidator->selector("form[action='" . $action . "']");
$jsValidator->ignore("[name!='some_hidden_but_required_input']:hidden");
```
> Allow multiple JsValidator instances

- .gitignore
- composer.json
- src/Support/DelegatedValidator.php
- tests/Javascript/ValidatorHandlerTest.php
- tests/JsValidationServiceProviderTest.php
- tests/JsValidatorFactoryTest.php
- tests/Remote/ResolverTest.php
- tests/Remote/ValidatorTest.php
- tests/Support/DelegatedValidatorTest.php
Laravel v5.3.21 (And 5.4) have breaking changes with the way `validator->getFiles()` and `validator->setFiles()` work.
This PR fixes #190 
Thanks to @reganjohnson
> Support for Laravel 5.3.21 and 5.4

- src/Javascript/JavascriptValidator.php
- src/Javascript/RuleParser.php
- src/JsValidatorFactory.php
- src/Support/DelegatedValidator.php
- tests/Javascript/JavascriptValidatorTest.php
e.g.,
* Rule `['items.*.name' => 'required']` will validate:
* DOM selector: `'[name="items\\[\\]\\[name\\]"]'`
* DOM attribute: `name="items[][name]"`
* Rule `['item_name.*' => 'required']` will validate:
* DOM selector: `'[name="item_name\\[\\]"]'`
* DOM attribute: `name="items_name[]"`
Laravel 5.2's `Validator::make()` immediately strips wildcard rules (since JsValidator's instantiation never includes data) so they must be tracked separately in the `DelegatedValidator` class.
Unfortunately named associative array keys are not yet supported in JavaScript as:
* The jQuery Validation plugin requires exact form `name=""` attribute values when defining rules and custom messages.
* `$(document).ready()` best-guess attempts to apply rules to `name=""` attributes on the page are made redundant …
> Support 0-indexed arrays for 5.2 validation wildcard rules

- src/Javascript/MessageParser.php
- src/JsValidatorFactory.php
- src/Remote/Validator.php
- src/Support/DelegatedValidator.php
- src/Support/ValidationRuleParserProxy.php
- tests/Javascript/MessageParserTest.php
- tests/Remote/ResolverTest.php
- tests/Remote/ValidatorTest.php
- tests/Support/DelegatedValidatorTest.php
- tests/stubs/JsValidatorFactoryTest.php
I've updated the code and the tests to work with Laravel 5.4 and thus created breaking changes against previous versions. I wasn't sure what to do with your testing setup as there are multiple `composer.json`'s for the different Laravel versions to be tested. But these don't seem to be needed anymore as the code changes I've done will break on previous Laravel versions.
I've had to create a proxy class for the `ValidationRuleParser` because its parse function is static and it didn't seem like you could mock static functions. I've done this to allow the `DelegatedValidator` to be tested. Annoyingly it will be the only class in your code base not being tested, so interested in what your thoughts are.
Thanks
Chris
> Laravel 5.4 Fixes with Tests

- .travis.yml
- tests/composer-5.0.json
- tests/composer-5.1.json
- tests/composer-5.2.json
- tests/composer-5.3.json
- tests/composer-5.4.json
- Add Travis CI tests for Laravel 5.4
- Cleanup test composers contents
> Add Travis CI tests for Laravel 5.4

- src/Javascript/MessageParser.php
In symfony 4.0+ Symfony\Component\HttpFoundation\File\UploadedFile strictly expects the fifth argument to be an integer. Passing an actual valid PHP error constant like UPLOAD_ERR_NO_FILE instead of a string fixes this error when working with file related validation rules like images, mimetypes, files. 
Without this fix the following error is thrown whenever a validation rule is used
```
Proengsoft\JsValidation\Javascript\JavascriptValidator::__toString() must not throw an exception, caught TypeError: Argument 5 passed to Symfony\Component\HttpFoundation\File\UploadedFile::__construct() must be of the type integer or null, string given, called in /home/vagrant/sites/gmodstore/vendor/proengsoft/laravel-jsvalidation/src/Javascript/MessageParser.php on line 106
```
This is a fix for #304
> [Laravel 5.6] Symfony no longer accepts a string as an error

- src/Support/DelegatedValidator.php
- tests/Support/DelegatedValidatorTest.php
Added check and conversion of Rule that's an object ref #313 
In addition to this fix, for custom rules, another error will be thrown by the Illuminate `ValidationRulesParser.php` about the object error. The solution to this is to define the `__toString` in your rule like so.. replacing the returned string with your rule name.
```php
public function __toString()
{
return 'USPhoneNumber';
}
```
> Fix for custom rules

- resources/views/bootstrap4.php
- Fix wrong class form-control for bootstrap 4
- Remove error class when the input value becomes correct.
> Fix wrong class for bootstrap4

- src/JsValidatorFactory.php
- src/Support/DelegatedValidator.php
- src/Support/ValidationRuleParserProxy.php
- tests/Support/DelegatedValidatorTest.php
`explodeRules` was moved out of `Validator` in https://github.com/laravel/framework/pull/17005/files
This PR resolves that issue.
> Fixed #245

- src/Javascript/JavascriptValidator.php
- src/JsValidatorFactory.php
- src/Support/DelegatedValidator.php
Mimics Laravel's `withValidator` function, see https://laravel.com/docs/5.8/validation
> **Adding After Hooks To Form Requests**
> If you would like to add an "after" hook to a form request, you may use the withValidator method. This method receives the fully constructed validator, allowing you to call any of its methods before the validation rules are actually evaluated:
```php
/**
* Configure the validator instance.
*
* @param  \Illuminate\Validation\Validator  $validator
* @return void
*/
public function withValidator($validator)
{
$validator->after(function ($validator) {
if ($this->somethingElseIsInvalid()) {
$validator->errors()->add('field', 'Something is wrong with this field!');
}
});
}
```
> Added withJsValidator

- src/JsValidatorFactory.php
Hello,
I'm currently upgrade a project to php7.4, and I use https://github.com/nunomaduro/larastan to help me to find some bugs.
And it find that the type of the parameter `$selector` in `JsValidatorFactory@formRequest` is defined as null type.
So I extend it to string
> extend type to string JsValidatorFactory@formRequest

- config/jsvalidation.php
- src/Javascript/JavascriptValidator.php
- src/JsValidatorFactory.php
- tests/Javascript/JavascriptValidatorTest.php
- tests/JsValidatorFactoryTest.php
Added a config option to set a default `ignore` value (https://jqueryvalidation.org/validate/#ignore)
Defaults to disabling contentEditable as this is how the package has always worked and there's a bug upstream in the way it handles elements with no name / id. See issue for more information this point.
> Fixes #424

- src/Javascript/MessageParser.php
- src/Javascript/RuleParser.php
- src/JsValidatorFactory.php
- tests/Javascript/MessageParserTest.php
- tests/Javascript/RuleParserTest.php
- tests/JsValidatorFactoryTest.php
Laravel validation converts `*` to `__asterisk__` in Laravel 6+ (https://github.com/laravel/framework/pull/31257).
helpers.js relies on `[*]` to parse those wildcard rules:
```js
regexFromWildcard: function(name) {
var nameParts = name.split("[*]");
```
Todo:
> Fixes #297

- .styleci.yml
- config/jsvalidation.php
- src/Javascript/RuleParser.php
- src/Javascript/ValidatorHandler.php
- src/JsValidatorFactory.php
- src/Support/DelegatedValidator.php
- src/Support/UseDelegatedValidatorTrait.php
- src/Support/ValidationRuleParserProxy.php
Style CI account was overridding `.style-ci.yml` for a long time. This is finally fixed so we can start using the integration again.
> Fixed Style CI

- package-lock.json
CVE-2020-7598
moderate severity
Vulnerable versions: < 0.2.1
Patched version: 0.2.1
minimist before 1.2.2 could be tricked into adding or modifying properties of Object.prototype using a "constructor" or "proto" payload.
> Updated minimist dependency (CVE-2020-7598)

- resources/assets/js/helpers.js
- resources/assets/js/jsvalidation.js
- resources/assets/js/validations.js
Replaces deprecated jQuery 3 functions listed at https://api.jquery.com/category/deprecated/
> Replaced deprecated jQuery functions

- .styleci.yml
Fixed The 'simplified_null_return' fixer cannot be disabled because it is not enabled by your preset.
> Fixed style ci config

- README.md
I was looking at the docs and noticed it doesn't say Laravel 8 is supported, even though Laravel 8 support was added in version [4.1.0](https://github.com/proengsoft/laravel-jsvalidation/releases/tag/4.1.0).
> Add Laravel 8 to supported versions in README

- .github/workflows/tests.yml
- README.md
No changes to source code, but dropping support for Laravel 5 releases. Testing against so any versions is burdensome.
> ci: stop testing on Laravel 5 releases

- .github/workflows/tests.yml
XDebug is not necessary and slows down the tests - the code coverage workflow is separate.
> ci: remove xdebug from tests workflow

- resources/assets/js/helpers.js
Added fix for issue #631
Fixes a problem introduced in 4.4.3 (Min and Max validation rules stopped working for arrays with keys as per issue #631) that was designed to address issue #613. 
The function `allElementValues` now looks for an empty array pattern in the string rather than the individual brackets.
> fix: min / max array rules

- .github/workflows/php-tests.yml
https://github.com/actions/cache/blob/main/examples.md#php---composer
> ci: cache composer dependencies

- resources/assets/js/helpers.js
Fixes #851 
This fixes a bug in date format rules.
Since kartik-v/php-date-formatter v1.3.4, `DateFormatter.parseDate()` returns `null` instead of `false` when input does not match expected format. This resulted in laravel-jsvalidation `DateFormat` rules always succeeding.
With this change, helper `parseTime()`:
- performs the same checks as Laravel `date_format` rule: try to parse input value, then format it back and compare the result with original input value
- returns `false` as it should when input does not match the expected date format
> fix: date format rules
